### ISSUE TITLE
Support log4j2's Message objects

### ISSUE THREAD

**Issue by iravid** [hseeberger/akka-log4j#15]
Hi @hseeberger, thanks for the great library! 

Support for logging Message objects directly would be very beneficial for structured logging, something most libraries do using MDC. MDC, however, is not threadsafe and generally painful to use in Akka (can't log from Future callbacks, for example).

I'll gladly send a PR for this feature. What do you think?

**Comment by hseeberger** [comment]
I don't think this will work, because akka-log4j is just a backend for the logging API of Akka which only allows for `String` messages.

**Comment by iravid** [comment]
True, but I was planning on implementing an alternative LoggingAdapter (and corresponding ActorLogging trait) that has an API that supports passing Message objects.

Since the Event stream supports passing AnyRefs around, should work fine.

**Comment by hseeberger** [comment]
I see. That's out of scope for this project, though.
