### ISSUE TITLE
Upgrade to Akka 2.4.2-RC1

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/akka-log4j#16]

**Comment by guidomedina** [comment]
Akka 2.4.3 released :D

**Comment by hseeberger** [comment]
LOL

**Comment by guidomedina** [comment]
I was saving issue numbers so they wouldn't run out of sequence !!!, hence decided to suggest you here that it is a good time for a new release and 2.4.3 so two birds one shot ;-)

**Comment by hseeberger** [comment]
Save all the resources ;-) I'm on it!

**Comment by hseeberger** [comment]
Released 1.1.3

**Comment by guidomedina** [comment]
Thanks, I started using it already, now my LMAX like mailbox is in use:
https://gist.github.com/guidomedina/b71b81bedd69c64a7b65

You could also use `MpscChunkedArrayQueue` from JCtools which will grow in chunks to minimize GC and give you the idea of theoretical infinite size, say:

`new MpscChunkedArrayQueue(1024, 1024 * 1024, true)`

That translates to a queue of initial size of 1024, max size of 1024 ^ 2 and grow of 1024 chunks size.

**Comment by guidomedina** [comment]
You could also use `MpscChunkedArrayQueue` from JCtools which will grow in chunks to minimize GC and give you the idea of theoretical infinite size, say:

`new MpscChunkedArrayQueue(1024, 1024 * 1024, true)`

That translates to a queue of initial size of 1024, max size of 1024 ^ 2 and grow of 1024 chunks.
