### ISSUE TITLE
SLF4J to Log4j Bridge missing

### ISSUE THREAD

**Issue by mdonkers** [hseeberger/akka-log4j#21]
Hi,

When adding akka-log4j I'm receiving the following error message:

```
[ERROR] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[ERROR] SLF4J: Defaulting to no-operation (NOP) logger implementation
[ERROR] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

This can be easily fixed by adding the following dependency:

```
"org.apache.logging.log4j" % "log4j-slf4j-impl" % Version.Log4j
```

It prevents other projects from having to add this library themselves.

BR,
Miel

**Comment by hseeberger** [comment]
Where does that error message come from?

**Comment by mdonkers** [comment]
When starting the application. I presume when SLF4J is being initialized. This is the full log upon application startup:

```
[info] Starting application coffee in the background ...
coffee Starting nl.codecentric.coffee.CoffeeApp.main()
[success] Total time: 0 s, completed Feb 20, 2016 8:46:25 PM
2. Waiting for source changes... (press enter to interrupt)
coffee[ERROR] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
coffee[ERROR] SLF4J: Defaulting to no-operation (NOP) logger implementation
coffee[ERROR] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

After I added the Log4J2 - SLF4J bridge:

```
[info] Application coffee not yet started
[info] Starting application coffee in the background ...
coffee Starting nl.codecentric.coffee.CoffeeApp.main()
[success] Total time: 0 s, completed Feb 22, 2016 10:03:04 AM
```

See also here: http://www.slf4j.org/codes.html#StaticLoggerBinder

**Comment by hseeberger** [comment]
Why is SLF4J used at all? This project is about Log4j. Could you please track down where in your app SLF4J is used? If you added it, please remove it or use that bridge, but in that case there's no need to add the bridge to this project.

**Comment by mdonkers** [comment]
Well, if I'm not mistaken then Akka Logging is depending on SLF4J as facade for other logging implementations; http://doc.akka.io/docs/akka/2.4.1/java/logging.html#SLF4J
So SLF4J comes with Akka automatically.

I don't fully understand why its still using Log4J to output the logging, so I'll look into that. But normally the bridge would always be necessary.

**Comment by hseeberger** [comment]
No, Akka is flexible with regard to logging backends. SLF4J is just one option as is Log4j. Please read the docs carefully ;-)

Which logging backend library are you using?
