### ISSUE TITLE
Log4j 2.6 issue or plugin?

### ISSUE THREAD

**Issue by guidomedina** [hseeberger/akka-log4j#30]
I just tested my application with Log4j 2.6 and it wouldn't even start, no error message, etc, I'm not sure if is related to akka-log4j or log4j 2.6 issue, I'm wondering if it can be reproduced by trying to run the tests?

**Comment by guidomedina** [comment]
Closing, my project was including both log4j-api 2.5 and 2.6, sorry for the hassle.

**Comment by hseeberger** [comment]
;-)
