### ISSUE TITLE
Pls, release new version

### ISSUE THREAD

**Issue by golem131** [hseeberger/akka-log4j#59]

**Comment by hseeberger** [comment]
Which new features do you expect?

**Comment by robvadai** [comment]
@hseeberger hi there, are you planning to bump the Akka library dependency version? The library is great but lacks behind in terms of Akka versioning.

**Comment by hseeberger** [comment]
This project is EOL. Please use akka-slf4j. You can still use log4j2 as a backend.

**Comment by hseeberger** [comment]
See README.
